### ISSUE TITLE
how about a node-red module?

### ISSUE THREAD

**Issue by stoneobscurity** [DoctorMcKay/node-blackvue#5]
it would be grand.

**Comment by DoctorMcKay** [comment]
What is "red"?

**Comment by stoneobscurity** [comment]
really? https://nodered.org/
https://www.youtube.com/watch?v=vYreeoCoQPI

**Comment by DoctorMcKay** [comment]
That site looks like more buzzwords than content, but my understanding is that it's like a visual way to tie together events and actions in IoT devices? I don't see how that would be useful here, as this module is pretty much just to retrieve video files from a camera. Maybe someday in the future I'll add cloud support (with notifications) but that day is probably not in the near future.

Either way, I don't have the time or interest to build a module for some other platform right now.
